checks:
  php: true

filter:
  paths:
    - "src/*"
  excluded_paths:
    - "src/ApplicationRunner.php"
    - "src/Installer.php"

build:
  image: default-bionic

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      environment:
        php:
          version: 8.0.11
          ini:
            "xdebug.mode": coverage

      dependencies:
        override:
          - composer self-update
          - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
          - sed -i "23 a require_once dirname(__DIR__) . '/C3.php';" public/index.php


      tests:
        override:
          - command: |
              php -S 127.0.0.1:8080 -t public public/index.php > ./runtime/yii.log 2>&1 &
              vendor/bin/codecept run --coverage-xml
            on_node: 1
            coverage:
              file: runtime/tests/_output/coverage.xml
              format: php-clover
