services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    env_file:
      - path: .env.test.example
      - path: .env.test
        required: false
    volumes:
      - ./:/app
      - ./runtime:/app/runtime
      - caddy_data:/data
      - caddy_config:/config
    tty: true
