#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Runner\ApplicationConsoleRunner;

define('YII_ENV', getenv('env') ?? 'production');

require_once __DIR__ . '/vendor/autoload.php';

$runnerConsole = new ApplicationConsoleRunner();

// Run application:
$runnerConsole->run();
