#!/usr/bin/env php
<?php

declare(strict_types=1);

use App\Runner\ConsoleApplicationRunner;

require_once __DIR__ . '/vendor/autoload.php';

// Run console application runner
$params = require_once __DIR__ . '/config/params-console-runner.php';
$consoleRunner = new ConsoleApplicationRunner($params['environment'] ?? null, $params['validateContainer'] ?? true);
$consoleRunner->run();
