services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: ..
      target: dev
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-develop}"
      APP_ENV: "${APP_ENV:-dev}"
      APP_DEBUG: ${APP_DEBUG:-true}
      SERVER_NAME: ":80"
      COMPOSER_CACHE_DIR: /app/runtime/cache/composer
    ports:
      - "${DEV_PORT:-80}:80"
    volumes:
      - ../:/app
      - ../runtime:/app/runtime
      - caddy_data:/data
      - caddy_config:/config
    tty: true

