services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: ..
      target: dev
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    environment:
      XDEBUG_MODE: "coverage"
      APP_ENV: "test"
      APP_DEBUG: "false"
      APP_C3: "true"
      SERVER_NAME: ":80"
      COMPOSER_CACHE_DIR: /app/runtime/cache/composer
    volumes:
      - ../:/app
      - ../runtime:/app/runtime
      - caddy_data:/data
      - caddy_config:/config
    tty: true

