name: Code Style

on:
  pull_request:
    paths:
      - '.github/workflows/cs.yml'
      - 'config/**'
      - 'public/index.php'
      - 'src/**'
      - 'tests/**'
      - '.php-cs-fixer.dist.php'
      - 'composer.json'
      - 'rector.php'
      - 'yii'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  cs-fix:
    name: cs-fix
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push PHP CS Fixer and Rector changes to pull requests
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0

      - name: Run PHP CS Fixer
        run: ./vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php

      - name: Run Rector
        run: ./vendor/bin/rector --output-format=github

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ github.token }}
          HEAD_REF: ${{ github.head_ref }}
          REPOSITORY: ${{ github.repository }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add '*.php'
          git diff --staged --quiet || git commit -m "Apply PHP CS Fixer and Rector changes (CI)"
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPOSITORY}.git" "HEAD:${HEAD_REF}"
